"""new column to diary

Revision ID: 793a035833d8
Revises: f193b5784405
Create Date: 2025-12-10 14:14:20.282897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793a035833d8'
down_revision: Union[str, None] = 'f193b5784405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('diary_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'diary_id')
    # ### end Alembic commands ###
