# get the python image
FROM python:3.11-slim

# set the working directory inside the container
WORKDIR /app

# copy my dependencies into the container
COPY requirements.txt .

# install all dependancy
RUN pip install -r requirements.txt

COPY . .

# Start app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]